### PR TITLE
Single quote -> double quote

### PR DESCRIPTION
**Pull request by epicfaace**

### CODE REVIEW

**Comment by h-m-f-t** [comment]
There's not universal consensus in American English on this, and in both instances, I'm not quoting other texts but instead referring to and highlighting the concept of the word/phrase. Feedback welcome, and maybe there's a suggestion on this in a CISA style guide (cc: @mark-cane)?, but I'm of a mind to keep this as is.

**Comment by epicfaace** [comment]
> There's not universal consensus in American English on this

Interesting, I wasn't aware of that -- I thought American English universally doesn't use single quotes for this usage (referring to and highlighting the concept of the word/phrase). The only thing I can think of is AP style's usage of single quotes in article headlines, but that wouldn't apply here. Do you have an example / other guideline where this usage of single quotes is used or encouraged?

**Comment by h-m-f-t** [comment]
_cites wikipedia_: https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction

I think we could just as easily italicize both words, though I think italicized hrefs look weird.

**Comment by mark-cane** [comment]
To my knowledge, there is not a CISA style guide which addresses this specifically. I did reach out to CSD Pubs, and they think the single quotes works. Also sent me this link, which I found relevant: https://en.wikipedia.org/wiki/Scare_quotes

**Comment by epicfaace** [comment]
Sounds good, thanks for the explanation!

**Pull request closed without merging**
